name: NPM publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 가져오기
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: 의존성 설치
        run: yarn install --frozen-lockfile

      - name: 프로젝트 빌드
        run: yarn build

      - name: NPM 배포
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
        run: npm publish --access public
